version: '3'

networks:
  event_driven_practice:
    external: true

services:
  email-service:
    image: node:14-alpine
    volumes:
      - ./:/app
      - ./.npmrcempty:/app/.npmrc
    working_dir: /app
    networks:
      - event_driven_practice
    env_file:
      - .env
    ports:
      - "6060:6060"
    command: "npm run start:dev"
